name: nanopore_allelic_methylation
channels: 
  - 'conda-forge'
  - 'bioconda'
  - 'r'
  - 'defaults'
dependencies:
  - bioconda::bioconductor-annotationhub
  - bioconda::bioconductor-biomart
  - bioconda::bioconductor-genomicranges
  - bioconda::bioconductor-rtracklayer
  - bioconda::bioconductor-dss
  - bioconda::bioconductor-bsseq
  - bioconda::bioconductor-rsamtools
  - bioconda::bioconductor-rsubread
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-glimma
  - bioconda::bioconductor-edger
  - bioconda::bioconductor-biocinstaller
  - bioconda::r-mclust
  - r::r-data.table
  - r::r-tidyverse
  - r::r-rmarkdown
  - r::r-viridis
  - r::r-gtable
  - r::r-knitr
  - r::r-gridextra
  - r::r-devtools
  - r::r-broom
  - r::r-glmnet
  - r::r-essentials
  - conda-forge::r-fuzzyjoin
  - conda-forge::r-cowplot
  - conda-forge::r-ggextra
  - bioconda::biopython
  - bioconda::pysam
  - bioconda::snakemake
  - conda-forge::future
  - conda-forge::numpy
  - bioconda::samtools
  - bioconda::bwa
  - bioconda::hisat2
  - bioconda::trim-galore
  - bioconda::snpsplit
  - bioconda::bismark
  - bioconda::nanopolish
  - conda-forge::pandoc