name: haplotyped_methylome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotationhub
  - bioconductor-biomart
  - bioconductor-bsseq
  - bioconductor-dss
  - bioconductor-edger
  - bioconductor-genomicranges
  - bioconductor-limma
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-rtracklayer
  - bismark
  - bowtie2
  - bwa
  - cutadapt
  - fastqc
  - hisat2
  - htslib
  - nanopolish
  - ont-fast5-api
  - pysam
  - samtools
  - snakemake
  - snpsplit
  - trim-galore
  - biopython
  - future
  - h5py
  - pandoc
  - progressbar33
  - r-broom
  - r-cowplot
  - r-data.table
  - r-devtools
  - r-fuzzyjoin
  - r-ggextra
  - r-glmnet
  - r-gridextra
  - r-gtable
  - r-knitr
  - r-mclust
  - r-rmarkdown
  - r-rpart
  - r-tidyverse
  - r-viridis
  - numpy
